apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-api
  labels:
    app: my-python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-api
  template:
    metadata:
      labels:
        app: my-python-api
    spec:
      containers:
        - name: python-api
          image: docker.io/duggana1994/my-python-api-build-by-jenkins:latest
          imagePullPolicy: IfNotPresent   # recommended
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: python-api-service
spec:
  type: NodePort
  selector:
    app: my-python-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
