- name: Provision VM with Minikube
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - conntrack
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Download kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.30.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Restart Docker to apply group changes
      service:
        name: docker
        state: restarted

    - name: Start Minikube (run as root to avoid docker group delay issue)
      become: yes
      command: minikube start --driver=virtualbox


