Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"   # Ubuntu 20.04
  config.vm.hostname = "minikube-vm"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 8080, host: 8080


  # VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

 # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    set -e

    echo "Updating packages..."
    sudo apt-get update -y

    echo "Installing Docker..."
    sudo apt-get install -y docker.io
    sudo usermod -aG docker vagrant

    echo "Installing kubectl..."
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x ./kubectl
    sudo mv ./kubectl /usr/local/bin/kubectl

    echo "Installing Minikube..."
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube
    sudo mv minikube /usr/local/bin/minikube

    echo "Starting Minikube with Docker driver..."
    sudo -u vagrant minikube start --driver=docker
  SHELL
end