name: Build & Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  IMAGE_NAME: duggana1994/my-python-api-build-by-github-actions
  TAG: latest

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG

#
